[build]
  command = "npm run build"
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.production.environment]
  REACT_APP_BASE_URL = 'https://backend-notenest.onrender.com'

[context.deploy-preview.environment]
  REACT_APP_BASE_URL = 'https://backend-notenest.onrender.com'

[context.branch-deploy.environment]
  REACT_APP_BASE_URL = 'https://backend-notenest.onrender.com'
